services:
  postgresql:
    container_name: postgresql
    image: postgres:14.2-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=edmondkirsch3142
    expose:
      - 3142
    restart: always
    command: -p 3142
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: docker/Dockerfile
    expose:
      - 8000
    restart: always
    depends_on:
      - postgresql
  nginx:
    container_name: nginx
    image: nginx:stable
    expose:
      - 8080:8080
    depends_on:
      - backend
    networks:
      - default
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db:
    driver: local
